### PR TITLE
Fixing memory leak and setting scope test to test dependencies

### PR DESCRIPTION
**Pull request by svendiedrichsen**
I set the scope to test for junit and mockito dependencies.

### CODE REVIEW

**Comment by svendiedrichsen** [comment]
Please consider this. It is pretty annoying to use a library which brings in test frameworks as compile-time dependencies.

**Comment by svendiedrichsen** [comment]
Ping. Please consider this.

**Comment by svendiedrichsen** [comment]
I have replaced the HashMap for the regex cache with a WeakHashMap to allow GC to collect memory when parser is under constant usage in server conditions.

Please evaluate and eventually consider this as well. We are using your parser in production and are having memory troubles with it.

Thanks. Cheers,
Sven

**Comment by svendiedrichsen** [comment]
Using java.util.Logger instead of System.out

**Comment by svendiedrichsen** [comment]
Making LRUCache thread-safe and use WeakReference for allowing the GC to remove cached instances when needed

**Comment by svendiedrichsen** [comment]
@skybber : Could you please have a look. Thank you. Cheers Sven

**Comment by skybber** [comment]
Thanks for PR, I have some notes to it:

* maven - accepted. We should fix maven dependency as you have
* Parser is not thread safe since SQLite driver is not thread safe, therefore it is not necessary to have the LRU cache thread safe. Please, use some external synchronization mechanism on parser entrypoints if you access the parser from multiple threads.
* WeakHashMap makes the regex cache useless. There could be at most 'select count(*) from udger_devicename_regex' ~ 60. Why do you have problem with 60 cached items?
* LOGGER - accepted (I was wrong about logging in the past)

Could you please extract new PR with maven + logger - I will merge it ASAP.

**Comment by svendiedrichsen** [comment]
Thanks for your reply but we are running high performance 24/7 servers serving millions of requests per day. A little math from our production environment may highlight our concerns.
* we host around 30 sites.
* we have 6 JVM per site.
* each JVM hosts one appserver containing dozens of services
* around 10 services of each site contain a pool of around 30 UdgerParser

Results: 10 ParserPools x 30 Parsers x 60 Patterns = **18000** cached Patterns

Concerning our performance department this results in about **230MB** memory per JVM **only** in the RegexCache.

We have a cache in place for parsing results to keep the amount of parsing as low as possible. That's why after some time the RegexPatterns are not needed regularly and extensively anymore.

You can't keep all the data in memory all the time. Good caches only keep the _currently required_ data in memory for as long as they need to provide it. To operate an 24/7 high load/ high performance system you _must_ enable the JVM to lose memory if it deems it to be obsolete.

I urge you to look into WeakReference/ Garbage Collection and what they are essential good for when working in such an environment as we are:
* https://community.oracle.com/blogs/enicholas/2006/05/04/understanding-weak-references
* http://javarevisited.blogspot.de/2014/03/difference-between-weakreference-vs-softreference-phantom-strong-reference-java.html
* https://en.wikipedia.org/wiki/Garbage_collection_(computer_science)

Please don't get me wrong. I don't mean this in any condescending way.

Cheers
Sven

**Comment by skybber** [comment]
I do know what the weakhasmap is... In our case we don't keep any references to keys. Therefore the cache can be blown in next GC run - means cache is useless with weak keys.

https://docs.oracle.com/javase/7/docs/api/java/util/WeakHashMap.html

_... Hash table based implementation of the Map interface, with weak keys. An entry in a WeakHashMap will automatically be removed when its key is no longer in ordinary use..._ 

I would suggest to add a new flag turning off the cache. Is it sufficient for you?

As far as memory usage - in your case 230M / 18.000 = 13k per pattern. 13k looks too much for me, may be I'm wrong.

**Comment by svendiedrichsen** [comment]
Useless after the GC run. Which means useful before and for as long as the time between two GC runs. But anyway turning off the cache would be detremental to performance. I think caching is vital. Especially for our system.

How about using SoftReference for the HashMaps value (Pattern). This will only be cleaned up if the system is low on memory just before the OutOfMemoryError?

Concerning the size of a compiled Pattern instance i will try to evaluate it.

**Comment by skybber** [comment]
Currently regexp cache is not so relevant since we have LRU cache now. The performance penalty will be no so big if it is turned off.  
  Soft keys are removed independetly on memory usage. Exact removal depends on GC implementation.

**Comment by svendiedrichsen** [comment]
I don't know what your knowledge about the different GC implementations and their handling of SoftReference are but I'll go with the JavaDoc.

**Comment by skybber** [comment]
Hi, as I wrote the concurrent maps are not necessary since Parser is not thread safe.

**Comment by skybber** [comment]
Looks very good. Thanks!

**Pull request merged**
