### PR TITLE
Fix performance problem by properly closing PreparedStatement

### PR DESCRIPTION
**Pull request by mgandin**
Hello,

We are actually planning to replace an open-source user-agent parser with udger-java in our codebase for lesfurets.com (a french web insurance comparator) .

We have saw some improvements to gain some performance in parsing. We have just fix your code with closing PreparedStatements (for 5000 user-agents, the run longs from 230 seconds to 80 seconds after optimizations).

We have keep a manually preparedstatements closing, if you plan to be compatible with java >= Java 7, the code can be improved with try-with-resources.

### CODE REVIEW

**Comment by skybber** [comment]
Hello,
I've tested your patch with the closing prepared statement after each request. It decreases parser performance by 50% in our tests. Have you some another example which can we use to compare performance after your patch applaying? Anyway closing prepared statement is absolutely relevant, but I suppose to do that in the parser's close() method before closing connection to not hit the performance.

**Comment by mgandin** [comment]
Can you show me your performance tests ?

By the way, our code is mostly something like this : 

```
List<String> userAgents = ... // retrieve a very big list of user-agents

UdgerParser parser = new UdgerParser("udgerdb_v3.dat");

List<UdgerResult> results = userAgents.stream()
.map(agent -> parser.parse(agent))
.collect(Collectors.toList());

// Analysis of the List<UdgerResult
```

Closing the prepareStatements has cleary improved the performance for this use case.

**Comment by skybber** [comment]
The code below is based on unit test. 
I've got following results on my hardware:
Current version:
**TOTAL Queries: 1300 time : 4504ms AVG : 288.59677/s**
Version vith closing prepared stmt:
**TOTAL Queries: 1300 time : 8502ms AVG : 152.89815/s**

```
public class UdgerPerformanceTest {
    private static JsonArray jsonArray;
    public static void main(String args[]) {
        InputStream is = UdgerUaTest.class.getResourceAsStream("test_ua.json");
        JsonReader jsonReader = javax.json.Json.createReader(is);
        jsonArray = jsonReader.readArray();
        for (int i=0; i<20; i++) {
            System.out.println("### Test : " + (i+1));
            testSerial();
        }
    }

    private static void testSerial() {
        UdgerParser up = null;
        try {
            up = new UdgerParser("udgerdb_v3.dat");
            up.prepareParser();
            long tm = 0;
            for (int j=0; j<100; j++) {
                for (int i=0; i < jsonArray.size(); i++) {
                    JsonObject jar = jsonArray.getJsonObject(i);
                    String query = jar.getJsonObject("test").getString("teststring");
                    try {
                        long prev = System.nanoTime();
                        UdgerUaResult ret = up.parseUa(query);
                        tm += System.nanoTime() - prev;
                    } catch (SQLException e) {
                        e.printStackTrace();
                    }
                }
            }
            long numQueries = 100 * jsonArray.size();
            System.out.println("TOTAL Queries: " + numQueries + " time : " + tm / 1000000 + "ms AVG : " + 1000000000 * numQueries / (float) tm + "/s");
            up.printTimeMap();
        } catch (SQLException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        } finally {
            if (up != null) {
                try {
                    up.close();
                } catch (IOException e) {
                }
            }
        }
    }

}
```

**Comment by mgandin** [comment]
Thanks, I will check today. But before that, I have a strange thing, I am on the master branch and I don't have any prepareParser method on UdgerParser class. Is it normal ?

**Comment by skybber** [comment]
Aha, comment out the prepareParser() now, it is for next version of parser (could be more than more than 10x faster)

**Comment by mgandin** [comment]
Well, here are the results on your master branch, without closing preparedstatements : 

```
### Test : 1
TOTAL Queries: 1300 time : 12088ms AVG : 107.540855/s
### Test : 2
TOTAL Queries: 1300 time : 10122ms AVG : 128.4216/s
### Test : 3
TOTAL Queries: 1300 time : 10182ms AVG : 127.66848/s
### Test : 4
TOTAL Queries: 1300 time : 10277ms AVG : 126.494385/s
### Test : 5
TOTAL Queries: 1300 time : 10205ms AVG : 127.38068/s
### Test : 6
TOTAL Queries: 1300 time : 9994ms AVG : 130.07042/s
### Test : 7
TOTAL Queries: 1300 time : 10316ms AVG : 126.00778/s
### Test : 8
TOTAL Queries: 1300 time : 9780ms AVG : 132.9123/s
### Test : 9
TOTAL Queries: 1300 time : 10025ms AVG : 129.67303/s
### Test : 10
TOTAL Queries: 1300 time : 10717ms AVG : 121.30001/s
### Test : 11
TOTAL Queries: 1300 time : 10610ms AVG : 122.51806/s
### Test : 12
TOTAL Queries: 1300 time : 9385ms AVG : 138.51202/s
### Test : 13
TOTAL Queries: 1300 time : 10241ms AVG : 126.93477/s
### Test : 14
TOTAL Queries: 1300 time : 9499ms AVG : 136.847/s
### Test : 15
TOTAL Queries: 1300 time : 9265ms AVG : 140.30939/s
### Test : 16
TOTAL Queries: 1300 time : 9625ms AVG : 135.06355/s
### Test : 17
TOTAL Queries: 1300 time : 10367ms AVG : 125.39357/s
### Test : 18
TOTAL Queries: 1300 time : 10832ms AVG : 120.00782/s
### Test : 19
TOTAL Queries: 1300 time : 10054ms AVG : 129.29706/s
### Test : 20
TOTAL Queries: 1300 time : 9453ms AVG : 137.52075/s
```

And here are the results with my commit closing preparedstatements : 

```
### Test : 1
TOTAL Queries: 1300 time : 7027ms AVG : 184.98999/s
### Test : 2
TOTAL Queries: 1300 time : 6331ms AVG : 205.3244/s
### Test : 3
TOTAL Queries: 1300 time : 5976ms AVG : 217.51668/s
### Test : 4
TOTAL Queries: 1300 time : 6071ms AVG : 214.13017/s
### Test : 5
TOTAL Queries: 1300 time : 6311ms AVG : 205.9724/s
### Test : 6
TOTAL Queries: 1300 time : 6145ms AVG : 211.54456/s
### Test : 7
TOTAL Queries: 1300 time : 6060ms AVG : 214.49524/s
### Test : 8
TOTAL Queries: 1300 time : 5679ms AVG : 228.90688/s
### Test : 9
TOTAL Queries: 1300 time : 5611ms AVG : 231.68742/s
### Test : 10
TOTAL Queries: 1300 time : 5843ms AVG : 222.46349/s
### Test : 11
TOTAL Queries: 1300 time : 5936ms AVG : 218.99493/s
### Test : 12
TOTAL Queries: 1300 time : 6132ms AVG : 211.99379/s
### Test : 13
TOTAL Queries: 1300 time : 6075ms AVG : 213.99167/s
### Test : 14
TOTAL Queries: 1300 time : 6145ms AVG : 211.53203/s
### Test : 15
TOTAL Queries: 1300 time : 5965ms AVG : 217.92119/s
### Test : 16
TOTAL Queries: 1300 time : 6282ms AVG : 206.91429/s
### Test : 17
TOTAL Queries: 1300 time : 6643ms AVG : 195.69356/s
### Test : 18
TOTAL Queries: 1300 time : 5490ms AVG : 236.78676/s
### Test : 19
TOTAL Queries: 1300 time : 6625ms AVG : 196.19994/s
### Test : 20
TOTAL Queries: 1300 time : 6289ms AVG : 206.71004/s
```

It's faster ;-) !

**Comment by skybber** [comment]
It looks very strange. Definitely prepared statement should be faster when it is used repeatedly. May be there is some difference in native parts of sqlite driver. I have tested the parser on linux, what OS are you using ? Native parts are placed in org.sqlite.native.*

**Comment by mgandin** [comment]
I'm on MacOSX

**Comment by anirban-roy** [comment]
Hey Guys, Are you going to merge this Pull request. Furthermore the library does not close the ResultSets which makes it a memory leech in the long run. We are facing issues in this regards. @skybber Any thoughts on this?

**Comment by skybber** [comment]
Hi, thanks for reminder, I've forgot for it. I'll go to fix it.

**Comment by skybber** [comment]
Memory leaks caused by unclosed ResultSets are fixed now at the new version **v1.0.4**. Original subject of this issue was about "closing PreparedStatements" not ResultSets. The original mechanism keep the PreparedStatemes open due performance (at Linux at least). Anyway there is limited number of opened PreparedStatements, that shouldn't be increasing during parser's life cycle. I'm keeping this issue open.

**Comment by anirban-roy** [comment]
Thanks @skybber for addressing us quickly. Could you please release the latest version of maven central. It still shows 1.0.3 version on maven.

**Comment by skybber** [comment]
I've released it some minutes ago, probably there is a delay on maven repository?

**Pull request closed without merging**
